# Generated by Django 2.0.2 on 2018-06-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='subsector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
