# Generated by Django 2.0.2 on 2018-06-25 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20180625_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_uuid',
            field=models.TextField(blank=True, default=uuid.uuid4, max_length=255, unique=True, verbose_name='Indicator UUID'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='level',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.TextField(),
        ),
    ]
