# Generated by Django 2.0.2 on 2018-06-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20180625_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='number',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='tags',
        ),
    ]
