# Generated by Django 2.0.2 on 2018-06-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_auto_20180626_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
