# Generated by Django 2.0.2 on 2018-08-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('can_add_indicator', 'Can Modify Indicator'),)},
        ),
        migrations.AddField(
            model_name='indicator',
            name='direction_of_change',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Direction of Change'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='question_format',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Question Format'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='unit_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Unit Description'),
        ),
    ]
